name: Node CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout code at repo root
      - name: Check out code
        uses: actions/checkout@v4
        with:
          path: ''   # ensures repo files are at workspace root

      # Set up Node.js (LTS) and cache npm
      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 'lts/*'
          cache: 'npm'

      # In
